=== csm10495/vscode-gitweblinks/shared/handler-schema.json
{
    "$schema": "http://json-schema.org/schema",
    "type": "object",
    "definitions": {
        "template": {
            "anyOf": [{ "type": "string" }, { "type": "array", "items": { "type": "string" } }]
        },
        "staticServer": {
            "type": "object",
            "properties": {
                "http": {
                    "type": "string",
                    "description": "The HTTP(S) URL of the remote server. This is used to match HTTP remote URLs and also used as the 'base' URL for links to files."
                },
                "ssh": {
                    "type": "string",
                    "description": "The SSH URL of the remote server. This is used to match SSH remote URLs."
                }
            },
            "required": ["http"],
            "additionalProperties": false
        },
        "dynamicServer": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "pattern": {
                        "type": "string",
                        "description": "A regular expression to match on a remote URL. The captured groups are provided to the `http` and `ssh` templates."
                    },
                    "http": {
                        "$ref": "#/definitions/template",
                        "description": "The template to build the HTTP(S) URL of the remote server.\n\nCaptured groups from `pattern` are made available via the `match` variable."
                    },
                    "ssh": {
                        "$ref": "#/definitions/template",
                        "description": "The template to build the SSH URL of the remote server.\n\nCaptured groups from `pattern` are made available via the `match` variable."
                    }
                },
                "required": ["pattern", "http", "ssh"],
                "additionalProperties": false
            }
        },
        "server": {
            "oneOf": [
                { "$ref": "#/definitions/staticServer" },
                { "$ref": "#/definitions/dynamicServer" }
            ]
        },
        "tests": {
            "type": "object",
            "properties": {
                "settings": {
                    "type": "object",
                    "description": "Settings to make available during all tests."
                },
                "createUrl": {
                    "type": "object",
                    "properties": {
                        "remotes": {
                            "$ref": "#/definitions/remoteTests",
                            "description": "Tests for different types of remote URLs."
                        },
                        "spaces": {
                            "$ref": "#/definitions/urlTest",
                            "description": "A test for a file path that contains spaces.\n\nThe branch is always 'master' and the file is always 'src/path spaces/file spaces.txt'."
                        },
                        "misc": {
                            "type": "array",
                            "items": { "$ref": "#/definitions/customTest" },
                            "description": "(Optional) Additional tests for any scenarios that are not covered by the standard tests."
                        },
                        "branch": {
                            "$ref": "#/definitions/urlTest",
                            "description": "A test for creating a link using the current branch.\n\nThe branch is always 'feature/test' and the file is always 'src/file.txt'."
                        },
                        "commit": {
                            "$ref": "#/definitions/urlTest",
                            "description": "A test for creating a link using the current commit hash.\n\nThe commit hash is made available to the template via the `commit` variable, and the file is always 'src/file.txt'."
                        },
                        "selection": {
                            "$ref": "#/definitions/selectionTests",
                            "description": "Tests for including the selected range in the URL."
                        }
                    },
                    "required": ["remotes", "spaces", "branch", "commit", "selection"],
                    "additionalProperties": false,
                    "description": "Defines the test cases for creating URLs."
                }
            },
            "required": ["createUrl"],
            "additionalProperties": false
        },
        "remoteTests": {
            "type": "object",
            "properties": {
                "settings": {
                    "type": "object",
                    "description": "Settings to make available during the test."
                },
                "http": {
                    "type": "string",
                    "description": "The HTTP(S) remote URL to test that does not contain a username."
                },
                "httpWithUsername": {
                    "type": "string",
                    "description": "The HTTP(S) remote URL to test that contains a username."
                },
                "ssh": {
                    "type": "string",
                    "description": "The SSH remote URL to test that does not start with 'ssh://'."
                },
                "sshWithProtocol": {
                    "type": "string",
                    "description": "The SSH remote URL to test that starts with 'ssh://'."
                },
                "result": {
                    "$ref": "#/definitions/template",
                    "description": "The URL that is expected to be created.\n\nThe current commit hash is available via the `commit` variable."
                }
            },
            "required": ["http", "httpWithUsername", "ssh", "sshWithProtocol", "result"],
            "additionalProperties": false
        },
        "urlTest": {
            "type": "object",
            "properties": {
                "settings": {
                    "type": "object",
                    "description": "Settings to make available during the test."
                },
                "remote": {
                    "type": "string",
                    "description": "The remote URL to test."
                },
                "result": {
                    "$ref": "#/definitions/template",
                    "description": "The URL that is expected to be created.\n\nThe current commit hash is available via the `commit` variable."
                }
            },
            "required": ["remote", "result"],
            "additionalProperties": false
        },
        "customTest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "description": "The name of the test."
                },
                "settings": {
                    "type": "object",
                    "description": "Settings to make available during the test."
                },
                "remote": {
                    "type": "string",
                    "description": "The remote URL to test."
                },
                "fileName": {
                    "type": "string",
                    "description": "The name of the file to test. Defaults to 'src/file.txt' if this property is not specified."
                },
                "branch": {
                    "type": "string",
                    "description": "The name of the branch to test. Defaults to 'master' if this property is not specified."
                },
                "type": {
                    "type": "string",
                    "enum": ["branch", "commit"],
                    "description": "The type of link to create. Defaults to 'branch' if this property is not specified."
                },
                "selection": {
                    "$ref": "#/definitions/customTestSelection",
                    "description": "The selected range to test. Defaults to no selected range if this property is not specified."
                },
                "result": {
                    "type": "string",
                    "description": "The URL that is expected to be created.\n\nThe current commit hash is available via the `commit` variable."
                }
            },
            "required": ["name", "remote", "result"],
            "additionalProperties": false
        },
        "customTestSelection": {
            "type": "object",
            "properties": {
                "startLine": {
                    "type": "number",
                    "description": "The one-based line number that the selection starts on."
                },
                "startColumn": {
                    "type": "number",
                    "description": "The one-based column number that the selection starts on."
                },
                "endLine": {
                    "type": "number",
                    "description": "The one-based line number that the selection ends on."
                },
                "endColumn": {
                    "type": "number",
                    "description": "The one-based column number that the selection ends on."
                }
            },
            "required": ["startLine", "startColumn", "endLine", "endColumn"],
            "additionalProperties": false
        },
        "selectionTests": {
            "type": "object",
            "properties": {
                "settings": {
                    "type": "object",
                    "description": "Settings to make available during the test."
                },
                "remote": {
                    "type": "string",
                    "description": "The remote URL to use in the tests."
                },
                "point": {
                    "$ref": "#/definitions/selectionPointTest",
                    "description": "A test for the selection having the same start and end point."
                },
                "singleLine": {
                    "$ref": "#/definitions/selectionSingleLineTest",
                    "description": "A test for the selection having different start and end points, but on the same line."
                },
                "multipleLines": {
                    "$ref": "#/definitions/selectionMultipleLinesTest",
                    "description": "A test for the selection having different start and end points and on different lines."
                }
            },
            "required": ["remote", "point", "singleLine", "multipleLines"],
            "additionalProperties": false
        },
        "selectionPointTest": {
            "type": "object",
            "properties": {
                "line": {
                    "type": "number",
                    "description": "The one-based line number that the selection is on."
                },
                "result": {
                    "type": "string",
                    "description": "The URL that is expected to be created.\n\nThe start and end columns of the selection are always 1.\n\nThe current commit hash is available via the `commit` variable."
                }
            },
            "required": ["line", "result"],
            "additionalProperties": false
        },
        "selectionSingleLineTest": {
            "type": "object",
            "properties": {
                "line": {
                    "type": "number",
                    "description": "The one-based line number that the selection is on."
                },
                "startColumn": {
                    "type": "number",
                    "description": "The one-based column number that the selection starts at."
                },
                "endColumn": {
                    "type": "number",
                    "description": "The one-based column number that the selection ends at."
                },
                "result": {
                    "type": "string",
                    "description": "The URL that is expected to be created.\n\nThe current commit hash is available via the `commit` variable."
                }
            },
            "required": ["line", "startColumn", "endColumn", "result"],
            "additionalProperties": false
        },
        "selectionMultipleLinesTest": {
            "type": "object",
            "properties": {
                "startLine": {
                    "type": "number",
                    "description": "The one-based line number that the selection starts on."
                },
                "startColumn": {
                    "type": "number",
                    "description": "The one-based column number that the selection starts on."
                },
                "endLine": {
                    "type": "number",
                    "description": "The one-based line number that the selection ends on."
                },
                "endColumn": {
                    "type": "number",
                    "description": "The one-based column number that the selection ends on."
                },
                "result": {
                    "type": "string",
                    "description": "The URL that is expected to be created.\n\nThe current commit hash is available via the `commit` variable."
                }
            },
            "required": ["startLine", "startColumn", "endLine", "endColumn", "result"],
            "additionalProperties": false
        }
    },
    "properties": {
        "$schema": { "type": "string" },
        "name": {
            "type": "string",
            "description": "The name of the remote server type."
        },
        "server": {
            "$ref": "#/definitions/server",
            "description": "The public server URLs.\n\nSpecifying this property indicates that the remote server is public."
        },
        "private": {
            "type": "string",
            "description": "The name of the settings property that defines the private server URLs.\n\nSpecifying this property indicates that the remote server is private."
        },
        "branch": {
            "type": "array",
            "items": { "type": "string" },
            "description": "The arguments to pass to Git to get the name of the current branch."
        },
        "url": {
            "$ref": "#/definitions/template",
            "description": "The template to build the URL of a file."
        },
        "selection": {
            "$ref": "#/definitions/template",
            "description": "The template to build the part of the URL that specifies the selection. This is appended to the result of rendering the `url` template."
        },
        "tests": {
            "$ref": "#/definitions/tests",
            "description": "The test data for the handler."
        }
    },
    "oneOf": [{ "required": ["server"] }, { "required": ["private"] }],
    "required": ["name", "branch", "url", "selection", "tests"]
}

=== csm10495/vscode-gitweblinks/shared/handlers/gitlab.json
{
    "$schema": "../handler-schema.json",
    "name": "GitLab",
    "server": {
        "http": "https://gitlab.com",
        "ssh": "git@gitlab.com"
    },
    "branch": ["rev-parse", "--abbrev-ref"],
    "url": "{{ base }}/{{ repository }}/-/blob/{{ ref | encode_uri }}/{{ file | encode_uri }}",
    "selection": "#L{{ startLine }}{% if startLine != endLine %}-{{ endLine }}{% endif %}",
    "tests": {
        "createUrl": {
            "remotes": {
                "http": "https://gitlab.com/foo/bar.git",
                "httpWithUsername": "https://username@gitlab.com/foo/bar.git",
                "ssh": "git@gitlab.com:foo/bar.git",
                "sshWithProtocol": "ssh://git@gitlab.com:foo/bar.git",
                "result": "https://gitlab.com/foo/bar/-/blob/master/src/file.txt"
            },
            "spaces": {
                "remote": "https://gitlab.com/foo/bar.git",
                "result": "https://gitlab.com/foo/bar/-/blob/master/src/path%20spaces/file%20spaces.txt"
            },
            "branch": {
                "remote": "https://gitlab.com/foo/bar.git",
                "result": "https://gitlab.com/foo/bar/-/blob/feature/test/src/file.txt"
            },
            "commit": {
                "remote": "https://gitlab.com/foo/bar.git",
                "result": "https://gitlab.com/foo/bar/-/blob/{{ commit }}/src/file.txt"
            },
            "selection": {
                "remote": "https://gitlab.com/foo/bar.git",
                "point": {
                    "line": 10,
                    "result": "https://gitlab.com/foo/bar/-/blob/master/src/file.txt#L10"
                },
                "singleLine": {
                    "line": 10,
                    "startColumn": 20,
                    "endColumn": 30,
                    "result": "https://gitlab.com/foo/bar/-/blob/master/src/file.txt#L10"
                },
                "multipleLines": {
                    "startLine": 10,
                    "startColumn": 20,
                    "endLine": 30,
                    "endColumn": 40,
                    "result": "https://gitlab.com/foo/bar/-/blob/master/src/file.txt#L10-30"
                }
            }
        }
    }
}

=== csm10495/vscode-gitweblinks/shared/handlers/bitbucket-cloud.json
{
    "$schema": "../handler-schema.json",
    "name": "Bitbucket Cloud",
    "server": {
        "http": "https://bitbucket.org",
        "ssh": "git@bitbucket.org"
    },
    "branch": ["rev-parse", "--abbrev-ref"],
    "url": "{{ base }}/{{ repository }}/src/{{ commit | encode_uri }}/{{ file | encode_uri }}{% if type != 'commit' %}?at={{ ref | encode_uri_component }}{% endif %}",
    "selection": "#lines-{{ startLine }}{% if startLine != endLine %}:{{ endLine }}{% endif %}",
    "tests": {
        "createUrl": {
            "remotes": {
                "http": "https://bitbucket.org/foo/bar.git",
                "httpWithUsername": "https://username@bitbucket.org/foo/bar.git",
                "ssh": "git@bitbucket.org:foo/bar.git",
                "sshWithProtocol": "ssh://git@bitbucket.org:foo/bar.git",
                "result": "https://bitbucket.org/foo/bar/src/{{ commit }}/src/file.txt?at=master"
            },
            "spaces": {
                "remote": "https://bitbucket.org/foo/bar.git",
                "result": "https://bitbucket.org/foo/bar/src/{{ commit }}/src/path%20spaces/file%20spaces.txt?at=master"
            },
            "branch": {
                "remote": "https://bitbucket.org/foo/bar.git",
                "result": "https://bitbucket.org/foo/bar/src/{{ commit }}/src/file.txt?at=feature%2Ftest"
            },
            "commit": {
                "remote": "https://bitbucket.org/foo/bar.git",
                "result": "https://bitbucket.org/foo/bar/src/{{ commit }}/src/file.txt"
            },
            "selection": {
                "remote": "https://bitbucket.org/foo/bar.git",
                "point": {
                    "line": 10,
                    "result": "https://bitbucket.org/foo/bar/src/{{ commit }}/src/file.txt?at=master#lines-10"
                },
                "singleLine": {
                    "line": 10,
                    "startColumn": 20,
                    "endColumn": 30,
                    "result": "https://bitbucket.org/foo/bar/src/{{ commit }}/src/file.txt?at=master#lines-10"
                },
                "multipleLines": {
                    "startLine": 10,
                    "startColumn": 20,
                    "endLine": 30,
                    "endColumn": 40,
                    "result": "https://bitbucket.org/foo/bar/src/{{ commit }}/src/file.txt?at=master#lines-10:30"
                }
            }
        }
    }
}

=== csm10495/vscode-gitweblinks/shared/handlers/azure-dev-ops-server.json
{
    "$schema": "../handler-schema.json",
    "name": "Azure Dev Ops Server",
    "private": "azureDevOpsServer",
    "branch": ["rev-parse", "--abbrev-ref"],
    "url": "{{ base }}/{{ repository }}?path=%2F{{ file | uri_component }}&version=G{{ type | slice:0,1 | upcase }}{{ ref | uri_component }}",
    "selection": [
        "&line={{ startLine }}",
        "{% if startLine == endLine %}",
        "{% if startColumn == endColumn %}",
        "&lineEnd={{ startLine | plus:1 }}&lineStartColumn=1&lineEndColumn=1",
        "{% else %}",
        "&lineStartColumn={{ startColumn }}&lineEndColumn={{ endColumn }}",
        "{% endif %}",
        "{% else %}",
        "&lineEnd={{ endLine }}&lineStartColumn={{ startColumn }}&lineEndColumn={{ endColumn }}",
        "{% endif %}"
    ],
    "tests": {
        "settings": {
            "azureDevOpsServer": [
                {
                    "http": "https://local-devops",
                    "ssh": "git@local-devops:22"
                }
            ]
        },
        "createUrl": {
            "remotes": {
                "http": "https://local-devops/collection/foo/_git/bar",
                "httpWithUsername": "https://user@local-devops/collection/foo/_git/bar",
                "ssh": "git@local-devops:22/collection/foo/_git/bar",
                "sshWithProtocol": "ssh://git@local-devops:22/collection/foo/_git/bar",
                "result": "https://local-devops/collection/foo/_git/bar?path=%2Fsrc%2Ffile.txt&version=GBmaster"
            },
            "spaces": {
                "remote": "https://local-devops/collection/foo/_git/bar",
                "result": "https://local-devops/collection/foo/_git/bar?path=%2Fsrc%2Fpath%20spaces%2Ffile%20spaces.txt&version=GBmaster"
            },
            "branch": {
                "remote": "https://local-devops/collection/foo/_git/bar",
                "result": "https://local-devops/collection/foo/_git/bar?path=%2Fsrc%2Ffile.txt&version=GBfeature%2Ftest"
            },
            "commit": {
                "remote": "https://local-devops/collection/foo/_git/bar",
                "result": "https://local-devops/collection/foo/_git/bar?path=%2Fsrc%2Ffile.txt&version=GC{{ commit }}"
            },
            "selection": {
                "remote": "https://local-devops/collection/foo/_git/bar",
                "point": {
                    "line": 10,
                    "result": "https://local-devops/collection/foo/_git/bar?path=%2Fsrc%2Ffile.txt&version=GBmaster&line=10&lineEnd=11&lineStartColumn=1&lineEndColumn=1"
                },
                "singleLine": {
                    "line": 10,
                    "startColumn": 20,
                    "endColumn": 30,
                    "result": "https://local-devops/collection/foo/_git/bar?path=%2Fsrc%2Ffile.txt&version=GBmaster&line=10&lineStartColumn=20&lineEndColumn=30"
                },
                "multipleLines": {
                    "startLine": 10,
                    "startColumn": 20,
                    "endLine": 30,
                    "endColumn": 40,
                    "result": "https://local-devops/collection/foo/_git/bar?path=%2Fsrc%2Ffile.txt&version=GBmaster&line=10&lineEnd=30&lineStartColumn=20&lineEndColumn=40"
                }
            }
        }
    }
}

=== csm10495/vscode-gitweblinks/shared/handlers/gitlab-enterprise.json
{
    "$schema": "../handler-schema.json",
    "name": "GitLab Enterprise",
    "private": "gitLabEnterprise",
    "branch": ["rev-parse", "--abbrev-ref"],
    "url": "{{ base }}/{{ repository }}/-/blob/{{ ref | uri }}/{{ file | uri }}",
    "selection": "#L{{ startLine }}{% if startLine != endLine %}-{{ endLine }}{% endif %}",
    "tests": {
        "settings": {
            "gitLabEnterprise": [
                {
                    "http": "https://local-gitlab",
                    "ssh": "git@local-gitlab"
                }
            ]
        },
        "createUrl": {
            "remotes": {
                "http": "https://local-gitlab/foo/bar.git",
                "httpWithUsername": "https://username@local-gitlab/foo/bar.git",
                "ssh": "git@local-gitlab:foo/bar.git",
                "sshWithProtocol": "ssh://git@local-gitlab:foo/bar.git",
                "result": "https://local-gitlab/foo/bar/-/blob/master/src/file.txt"
            },
            "spaces": {
                "remote": "https://local-gitlab/foo/bar.git",
                "result": "https://local-gitlab/foo/bar/-/blob/master/src/path%20spaces/file%20spaces.txt"
            },
            "branch": {
                "remote": "https://local-gitlab/foo/bar.git",
                "result": "https://local-gitlab/foo/bar/-/blob/feature/test/src/file.txt"
            },
            "commit": {
                "remote": "https://local-gitlab/foo/bar.git",
                "result": "https://local-gitlab/foo/bar/-/blob/{{ commit }}/src/file.txt"
            },
            "selection": {
                "remote": "https://local-gitlab/foo/bar.git",
                "point": {
                    "line": 10,
                    "result": "https://local-gitlab/foo/bar/-/blob/master/src/file.txt#L10"
                },
                "singleLine": {
                    "line": 10,
                    "startColumn": 20,
                    "endColumn": 30,
                    "result": "https://local-gitlab/foo/bar/-/blob/master/src/file.txt#L10"
                },
                "multipleLines": {
                    "startLine": 10,
                    "startColumn": 20,
                    "endLine": 30,
                    "endColumn": 40,
                    "result": "https://local-gitlab/foo/bar/-/blob/master/src/file.txt#L10-30"
                }
            }
        }
    }
}

=== csm10495/vscode-gitweblinks/shared/handlers/github.json
{
    "$schema": "../handler-schema.json",
    "name": "GitHub",
    "server": {
        "http": "https://github.com",
        "ssh": "git@github.com"
    },
    "branch": ["rev-parse", "--abbrev-ref"],
    "url": "{{ base }}/{{ repository }}/blob/{{ ref | uri }}/{{ file | uri }}",
    "selection": "#L{{ startLine }}{% if startLine != endLine %}-L{{ endLine }}{% endif %}",
    "tests": {
        "createUrl": {
            "remotes": {
                "http": "https://github.com/foo/bar.git",
                "httpWithUsername": "https://username@github.com/foo/bar.git",
                "ssh": "git@github.com:foo/bar.git",
                "sshWithProtocol": "ssh://git@github.com:foo/bar.git",
                "result": "https://github.com/foo/bar/blob/master/src/file.txt"
            },
            "spaces": {
                "remote": "https://github.com/foo/bar.git",
                "result": "https://github.com/foo/bar/blob/master/src/path%20spaces/file%20spaces.txt"
            },
            "branch": {
                "remote": "https://github.com/foo/bar.git",
                "result": "https://github.com/foo/bar/blob/feature/test/src/file.txt"
            },
            "commit": {
                "remote": "https://github.com/foo/bar.git",
                "result": "https://github.com/foo/bar/blob/{{ commit }}/src/file.txt"
            },
            "selection": {
                "remote": "https://github.com/foo/bar.git",
                "point": {
                    "line": 10,
                    "result": "https://github.com/foo/bar/blob/master/src/file.txt#L10"
                },
                "singleLine": {
                    "line": 10,
                    "startColumn": 20,
                    "endColumn": 30,
                    "result": "https://github.com/foo/bar/blob/master/src/file.txt#L10"
                },
                "multipleLines": {
                    "startLine": 10,
                    "startColumn": 20,
                    "endLine": 30,
                    "endColumn": 40,
                    "result": "https://github.com/foo/bar/blob/master/src/file.txt#L10-L30"
                }
            }
        }
    }
}
